events {}

http {

    server {

        listen 80;

        # Core API Routing
        location /api/v1/orders {
            proxy_pass http://order-service:3000;
        }

        location /api/v1/inventories {
            proxy_pass http://inventory-service:80;
        }

        location /api/v1/expeditions {
            proxy_pass http://expedition-service:8000;
        }

        # Swagger UI Entrypoints
        location /orders/documentation {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://order-service:3000/api/documentation;
        }

        location /inventories/documentation {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://inventory-service:80/api/documentation;
        }

        location /expeditions/documentation {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://expedition-service:8000/api/documentation;
        }

        # Swagger UI assets & spec JSON routing using Referer header
        location ~ ^/(docs|api-docs|api/oauth2-callback) {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            if ($http_referer ~* /orders/documentation) {
                proxy_pass http://order-service:3000;
            }
            if ($http_referer ~* /inventories/documentation) {
                proxy_pass http://inventory-service:80;
            }
            if ($http_referer ~* /expeditions/documentation) {
                proxy_pass http://expedition-service:8000;
            }
        }
    }
}