events {}

http {

    server {

        listen 80;

        location /api/v1/orders {
            proxy_pass http://order-service:3000;
        }

        location /api/v1/inventories {
            proxy_pass http://inventory-service:80;
        }

        location /api/v1/expeditions {
            proxy_pass http://expedition-service:8000;
        }

    }

}